project_id = "gdklfxqbocvoxcfthysy"

[functions.slack-events]
verify_jwt = false

[functions.mbr-reminders]
verify_jwt = false

[functions.slack-activity-check]
verify_jwt = false

[functions.staffing-capacity-reminders]
verify_jwt = false