import type { Scorecard } from "./types";

export const growthLeadScorecard: Scorecard = {
  key: "growth_lead",
  label: "SEO Growth Lead",
  roleCategoryMatch: /seo growth lead/i,
  areas: [
    {
      id: "a1",
      name: "Outcome-led Growth & Portfolio Performance",
      short: "Growth & Portfolio",
      weight: 0.35,
      kpis: [
        { id: "k1", name: "Organic Traffic & Conversions", target: "100% KPI achievement / month", measure: "GA4 · GSC · Ahrefs / Semrush",
          def: "100% achievement of NB traffic and organic traffic coverage targets; 100% achievement of leads and organic conversions across all managed accounts.",
          bands: ["100% of targets achieved", "90–99% achieved", "75–89% achieved", "Below 75% achieved"] },
        { id: "k2", name: "Non-brand Traffic & Impressions", target: "100% NB traffic & impression targets", measure: "GSC non-brand filter · GA4 · Semrush / Ahrefs",
          def: "100% achievement of non-brand organic traffic and impression growth targets; expand the non-brand keyword footprint and query coverage across all managed accounts.",
          bands: ["100% of targets achieved", "90–99% achieved", "75–89% achieved", "Below 75% achieved"] },
        { id: "k3", name: "GEO Visibility — Brand Mentions", target: "100% brand mention visibility target", measure: "Semrush AI toolkit / Profound",
          def: "Achieve targeted brand mention share and frequency in AI answer engines (ChatGPT, Perplexity, Gemini, Google AI Overviews) for each account's priority prompt set.",
          bands: ["100% of target achieved", "90–99% achieved", "75–89% achieved", "Below 75% achieved"] },
        { id: "k4", name: "GEO Visibility — Domain Prompt Presence & Citations", target: "100% domain prompt presence target", measure: "Prompt tracking dashboard",
          def: "Achieve targeted domain citation / presence rate across the tracked prompt taxonomy — branded, competitor / comparison, endemic offensive & defensive prompts — for each account.",
          bands: ["100% of target achieved", "90–99% achieved", "75–89% achieved", "Below 75% achieved"] },
        { id: "k5", name: "Search Opportunity Experiments", target: "4+ experiments per cycle", measure: "Opportunity tracker",
          def: "Define and sign off on 4+ new search opportunities / experiments targeting the next 40–50% organic traffic growth horizon.",
          bands: ["4+ quality experiments signed off", "3 experiments", "2 experiments", "Fewer than 2 experiments"] },
      ],
    },
    {
      id: "a2",
      name: "Client Satisfaction & Retention",
      short: "Client & Retention",
      weight: 0.20,
      kpis: [
        { id: "k6", name: "Client Revenue, Retention & Expansion", target: "95% retention · 90% good · 85% avg · <80% poor", measure: "Retention reports",
          def: "Maintain 95% retention rate; identify and pursue upsell / expansion opportunities across all managed accounts.",
          bands: ["Strong retention + upsell growth", "Stable retention", "Moderate churn risk", "Client losses"] },
        { id: "k7", name: "CSAT & Client Sentiment", target: "CSAT ≥ 8/10", measure: "CSAT · NPS · client feedback",
          def: "Maintain CSAT ≥ 8/10 with proactive communication, trust-building and strategic alignment across all client touchpoints.",
          bands: ["Strong trust & proactive comms", "Healthy relationships", "Reactive engagement", "Escalation-heavy"] },
        { id: "k8", name: "Escalation Resolution", target: "Resolution within 48 hrs", measure: "Escalation tracker · CS & VSD feedback",
          def: "Resolve escalations within 48 hours; quality of delivery timelines and issue handling as measured by CS & VSD feedback.",
          bands: ["Proactive, within SLA", "Most issues resolved on time", "Delayed resolutions", "Escalation failures"] },
        { id: "k9", name: "Account Case Studies", target: "1 case study per quarter", measure: "Case study log",
          def: "Curate and publish high-quality account case studies documenting impact, methodology and results for internal and client-facing use.",
          bands: ["Regular, high-quality case studies", "Periodic case studies", "Occasional case studies", "Absent"] },
      ],
    },
    {
      id: "a3",
      name: "Pepper Platform Adoption — AI Transformation & Operational Efficiency",
      short: "AI & Platform Adoption",
      weight: 0.25,
      kpis: [
        { id: "k10", name: "Proprietary AI Workflows on Pepper Platform", target: "1+ workflow per month", measure: "Automation implementation count",
          def: "Implement 1+ proprietary Pepper Agent / AI workflows per month on Pepper Platform; drive significant AI-led efficiency gains across the team.",
          bands: ["Significant AI-led efficiency gains", "Good adoption", "Limited experiments", "Resistance to adoption"] },
        { id: "k11", name: "Atlas Adoption & AI Roadmap", target: "1 hr daily Atlas immersion", measure: "Internal product meeting logs",
          def: "Lead product, automation and AI roadmap discussions with Pepper's internal teams; champion and drive Atlas adoption.",
          bands: ["Leading the roadmap", "Active contributor", "Passive participation", "Disengaged"] },
        { id: "k12", name: "Resource & Time Optimization", target: "Improved delivery efficiency", measure: "Productivity reports",
          def: "Reduce operational overhead and improve delivery systems; track productivity improvements through AI-driven process optimization.",
          bands: ["Highly optimized systems", "Stable workflows", "Bottlenecks present", "Inefficient systems"] },
      ],
    },
    {
      id: "a4",
      name: "Team Performance, Operations & Delivery Quality",
      short: "Team & Delivery",
      weight: 0.20,
      kpis: [
        { id: "k13", name: "Team Productivity & Output Quality", target: "Avg team scorecard > 8/10", measure: "Team scorecards",
          def: "Drive average team scorecard score above 8/10; ensure high delivery quality, accountability and efficiency across all SEO managers.",
          bands: ["High-performing team", "Stable team output", "Frequent follow-ups needed", "Delivery instability"] },
        { id: "k14", name: "SEO / GEO Reporting Insights", target: "1 documented win per week", measure: "Weekly insights log · reporting channel",
          def: "Share one documented win or learning per week explaining what worked (and why) across SEO / GEO initiatives; circulate insights to the team and clients where relevant.",
          bands: ["Weekly, high-quality insights", "Most weeks covered", "Sporadic insights", "Absent"] },
        { id: "k15", name: "SEO & GEO Strategy Documentation", target: "1 updated doc per account per quarter", measure: "Strategy doc repository · quarterly review log",
          def: "Maintain an up-to-date SEO & GEO strategy document for every managed account — objectives, roadmap, active experiments and playbooks — reviewed and refreshed quarterly.",
          bands: ["All accounts documented & current", "Mostly current", "Partial or outdated", "Missing documentation"] },
        { id: "k16", name: "Deliverable Review Accuracy", target: "Minimal revisions & escalations", measure: "QA review score",
          def: "Minimal revisions and escalations across audits, strategies and reports; consistent QA checks on all outputs.",
          bands: ["No errors", "Minor improvements only", "Frequent misses", "Major quality concerns"] },
        { id: "k17", name: "Aligned Cross-team Operations", target: "Weekly structured standups", measure: "Standup cadence log · CS feedback",
          def: "Drive aligned operations across CS (VSD & BOPM) teams through structured standups; reduce silos and improve delivery coordination.",
          bands: ["Full cross-team alignment", "Good coordination", "Occasional gaps", "Siloed operations"] },
        { id: "k18", name: "Coaching & Capability Building", target: "1 initiative / month + quarterly program", measure: "Training logs · team feedback",
          def: "1+ coaching initiative per month; design and organize quarterly tech training and leadership programs to elevate team capability.",
          bands: ["Strong development culture", "Regular coaching", "Inconsistent coaching", "Weak capability building"] },
      ],
    },
  ],
};