import type { Scorecard } from "./types";

export const seoOpsScorecard: Scorecard = {
  key: "seo_ops",
  label: "SEO Ops",
  roleCategoryMatch: /seo operations/i,
  areas: [
    {
      id: "a1",
      name: "Outcome-led Growth & Portfolio Performance",
      short: "Growth & Portfolio",
      weight: 0.30,
      kpis: [
        { id: "k1", name: "Organic Traffic & Conversions", target: "100% KPI achievement / month", measure: "GA4 · GSC · Ahrefs / Semrush",
          def: "100% achievement of NB traffic and organic traffic coverage targets; 100% achievement of leads and organic conversions across all managed accounts.",
          bands: ["100% of targets achieved", "90–99% achieved", "75–89% achieved", "Below 75% achieved"] },
        { id: "k2", name: "Non-brand Traffic & Impressions", target: "100% NB traffic & impression targets", measure: "GSC non-brand filter · GA4 · Semrush / Ahrefs",
          def: "100% achievement of non-brand organic traffic and impression growth targets; expand the non-brand keyword footprint and query coverage across all managed accounts.",
          bands: ["100% of targets achieved", "90–99% achieved", "75–89% achieved", "Below 75% achieved"] },
        { id: "k3", name: "GEO Visibility — Brand Mentions", target: "100% brand mention visibility target", measure: "Semrush AI toolkit / Profound",
          def: "Achieve targeted brand mention share and frequency in AI answer engines (ChatGPT, Perplexity, Gemini, Google AI Overviews) for the priority prompt set of each managed account.",
          bands: ["100% of target achieved", "90–99% achieved", "75–89% achieved", "Below 75% achieved"] },
        { id: "k4", name: "GEO Visibility — Domain Prompt Presence", target: "100% domain prompt presence target", measure: "Prompt tracking dashboard",
          def: "Achieve targeted domain citation / presence rate across the tracked prompt taxonomy — branded, competitor / comparison, endemic offensive & defensive prompts — for each account.",
          bands: ["100% of target achieved", "90–99% achieved", "75–89% achieved", "Below 75% achieved"] },
        { id: "k5", name: "Search Opportunity Experiments", target: "4+ experiments per cycle", measure: "Opportunity tracker",
          def: "Define and sign off on 4+ new search opportunities / experiments targeting the next 40–50% organic traffic growth horizon.",
          bands: ["4+ quality experiments", "3 experiments", "2 experiments", "Fewer than 2"] },
      ],
    },
    {
      id: "a2",
      name: "Client Satisfaction & Retention",
      short: "Client & Retention",
      weight: 0.20,
      kpis: [
        { id: "k6", name: "Client Revenue, Retention & Expansion", target: "90% good · 85% avg · <80% poor", measure: "Retention reports",
          def: "Maintain 95% retention rate; identify and pursue upsell / expansion opportunities across all managed accounts.",
          bands: ["Strong retention + upsell growth", "Stable retention", "Moderate churn risk", "Client losses"] },
        { id: "k7", name: "CSAT & Client Sentiment", target: "CSAT ≥ 8/10", measure: "CSAT · NPS · client feedback",
          def: "Maintain CSAT ≥ 8/10 with proactive communication, trust-building and strategic alignment across all client touchpoints.",
          bands: ["Strong trust & proactive comms", "Healthy relationships", "Reactive engagement", "Escalation-heavy"] },
        { id: "k8", name: "Escalation Resolution", target: "Resolution ≤ 48 hrs", measure: "Escalation tracker · CS & VSD feedback",
          def: "Resolve escalations within 48 hours; quality of delivery timelines and issue handling as measured by CS & VSD feedback.",
          bands: ["Proactive, within SLA", "Most issues resolved on time", "Delayed resolutions", "Escalation failures"] },
      ],
    },
    {
      id: "a3",
      name: "Pepper Platform Adoption — AI Transformation & Operational Efficiency",
      short: "AI & Platform Adoption",
      weight: 0.25,
      kpis: [
        { id: "k9", name: "Proprietary AI Workflows on Pepper Platform", target: "1+ workflow per month", measure: "Automation implementation count",
          def: "Implement 1+ proprietary Pepper Agent / AI workflows per month on Pepper Platform; drive significant AI-led efficiency gains across the team.",
          bands: ["Significant AI-led efficiency gains", "Good adoption", "Limited experiments", "Resistance to adoption"] },
        { id: "k10", name: "Atlas Adoption & AI Roadmap", target: "1 hr daily Atlas immersion", measure: "Internal product meeting logs",
          def: "Lead product, automation and AI roadmap discussions with Pepper's internal teams; champion and drive Atlas adoption.",
          bands: ["Leading the roadmap", "Active contributor", "Passive participation", "Disengaged"] },
        { id: "k11", name: "Resource & Time Optimization", target: "Improved delivery efficiency", measure: "Productivity reports",
          def: "Reduce operational overhead and improve delivery systems; track productivity improvements through AI-driven process optimization.",
          bands: ["Highly optimized systems", "Stable workflows", "Bottlenecks present", "Inefficient systems"] },
      ],
    },
    {
      id: "a4",
      name: "Operational Excellence & Delivery Quality",
      short: "Delivery Quality",
      weight: 0.25,
      kpis: [
        { id: "k12", name: "SEO / GEO Reporting Insights", target: "1 documented win per week", measure: "Weekly insights log · reporting channel",
          def: "Share one documented win or learning per week explaining what worked (and why) across SEO / GEO initiatives; circulate insights to the team and clients where relevant.",
          bands: ["Weekly, high-quality insights", "Most weeks covered", "Sporadic insights", "Absent"] },
        { id: "k13", name: "SEO & GEO Strategy Documentation", target: "1 updated doc per account per quarter", measure: "Strategy doc repository · quarterly review log",
          def: "Maintain an up-to-date SEO & GEO strategy document for every managed account — objectives, roadmap, active experiments and playbooks — reviewed and refreshed quarterly.",
          bands: ["All accounts documented & current", "Mostly current", "Partial or outdated", "Missing documentation"] },
        { id: "k14", name: "Content Brief Accuracy & Quality", target: "No major revisions on submission", measure: "Review score · content performance",
          def: "Creation of high-quality SEO + GEO briefs with NLP terms, search intent, internal links, FAQs and optimization recommendations.",
          bands: ["No revisions", "Minor revisions", "Frequent corrections", "Major quality concerns"] },
        { id: "k15", name: "Technical SEO Audit Quality", target: "90% critical issues identified", measure: "Technical audit score",
          def: "Identify and prioritise technical SEO + GEO issues impacting growth; 90% of critical issues covered in audits.",
          bands: ["No revisions", "Minor revisions", "Major misses", "Critical gaps"] },
        { id: "k16", name: "SLA & Timely Delivery", target: "95% on-time completion", measure: "Task tracker / PM tool",
          def: "Ensure all deliverables are completed within committed timelines; 95%+ on-time completion rate.",
          bands: ["100% SLA", "90–95%", "80–89%", "Below 80%"] },
        { id: "k17", name: "SOP & Workflow Improvements", target: "1 process improvement / month", measure: "SOP submissions · automation count",
          def: "Contribute toward improving internal SEO + GEO systems and workflows; submit at least 1 process improvement per month.",
          bands: ["High-impact improvement", "Useful improvement", "Minor tweak", "None"] },
      ],
    },
  ],
};