// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id and email, useful for verifying the MCP connection.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = { user_id: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-deals.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_deals_default = defineTool2({
  name: "list_deals",
  title: "List deals",
  description: "List deals the signed-in user can access, honoring the app's row-level security. Optionally filter by a search string that matches deal id, VSD, or BOPM.",
  inputSchema: {
    search: z.string().trim().max(200).optional().describe("Optional substring filter"),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("staffing_deals").select("id, client_id, vsd, principal_bopm, senior_bopm, bopm").limit(limit ?? 50);
    if (search && search.length > 0) {
      const escaped = search.replace(/[%,]/g, "");
      query = query.or(
        `id.ilike.%${escaped}%,vsd.ilike.%${escaped}%,principal_bopm.ilike.%${escaped}%,senior_bopm.ilike.%${escaped}%,bopm.ilike.%${escaped}%`
      );
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { deals: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gdklfxqbocvoxcfthysy";
var mcp_default = defineMcp({
  name: "cx-os-mcp",
  title: "CX OS",
  version: "0.1.0",
  instructions: "Tools for CX OS. Use `whoami` to confirm the connection and `list_deals` to read the signed-in user's accessible deals (RLS-enforced).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_deals_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
