-- Sync staffing_people from canonical Google Sheet roster.
WITH incoming(id, name, department, designation, reporting_manager) AS (
  VALUES
('P394', 'Nikhil Somani', 'Capability - Creative Team', 'Creative Director - Strategy and Planning', 'Sneha Iyer'),
('P397', 'Pratyush Singh', 'Capability - Creative Team', 'Associate Group Head - Strategy', 'Barbie Duggal'),
('P452', 'Ansh Bhansali', 'Capability - Creative Team', 'Associate Group Head - Strategy', 'Nikhil Somani'),
('P458', 'Avantika Jain', 'Capability - Creative Team', 'Associate Creative Director - Strategy', 'Sneha Iyer'),
('P479', 'Barbie Duggal', 'Capability - Creative Team', 'ACD - Copy', 'Nikhil Somani'),
('P512', 'Viraj Ghodgaonkar', 'Capability - Creative Team', 'Senior Creative Director', 'Sneha Iyer'),
('P520', 'Zigyasa Tryoon', 'Capability - Creative Team', 'Group Head - Strategy', 'Nikhil Somani'),
('P524', 'Ashlesh Patil', 'Capability - Creative Team', 'Associate Creative Director - Design', 'Viraj Ghodgaonkar'),
('P527', 'Nishant Dhuriya', 'Capability - Creative Team', 'Associate Creative Director - Design', 'Viraj Ghodgaonkar'),
('P548', 'Snigdha Parasrampuria', 'Capability - Creative Team', 'Manager - Influencer Marketing', 'Sneha Iyer'),
('P555', 'Viwanshu Vaibhaw', 'Capability - Creative Team', 'Group Head Copy', 'Nikhil Somani'),
('P568', 'Stefan Amanna', 'Capability - Creative Team', 'Creative Director', 'Sneha Iyer'),
('P376', 'Remya Scaria', 'Capability - Digital Strategy', 'Associate Director - Digital Strategy', 'Ekta Desai'),
('P385', 'Shreya Shah', 'Capability - Digital Strategy', 'Manager - Content Strategy', 'Ekta Desai'),
('P468', 'Ekta Desai', 'Capability - Digital Strategy', 'Director - Digital Strategy', 'Kishan Panpalia'),
('P498', 'Alisha Bhargavan', 'Capability - Digital Strategy', 'Senior Associate - Digital Strategy', 'Shreya Shah'),
('P526', 'Irfan Pasha I', 'Capability - Digital Strategy', 'SEO Group Head', 'Ekta Desai'),
('P532', 'Arindam Sinha', 'Capability - Digital Strategy', 'Senior Manager - Digital Strategy', 'Ekta Desai'),
('P028', 'Gaurab Chatterjee', 'Capability - Quality Team', 'Senior Director - Content', 'Anirudh Singla'),
('P111', 'Pratima K', 'Capability - Quality Team', 'Associate Director - Content', 'Gaurab Chatterjee'),
('P122', 'Pathik Bhowmik', 'Capability - Quality Team', 'Associate Director - Content', 'Gaurab Chatterjee'),
('P285', 'Conchita Fernandes', 'Capability - Quality Team', 'Senior Content Lead', 'Pratima'),
('P364', 'Afshaan Khan', 'Capability - Quality Team', 'Senior Content Lead', 'Pathik Bhowmik'),
('P365', 'Jishana Balakrishnan', 'Capability - Quality Team', 'Senior Content Lead', 'Pathik Bhowmik'),
('P366', 'Greeshma A P', 'Capability - Quality Team', 'Associate Director - Content', 'Gaurab Chatterjee'),
('P400', 'Mitchelle Joseph', 'Capability - Quality Team', 'Quality Success Manager (BFSI)', 'Aditya Shaw'),
('P464', 'Anita Raghav', 'Capability - Quality Team', 'Associate Director - Content', 'Gaurab Chatterjee'),
('P496', 'Utsab Biswas', 'Capability - Quality Team', 'Senior Content Lead', 'Pathik Bhowmik'),
('P503', 'Nishtha Kanal', 'Capability - Quality Team', 'Senior Content Lead', 'Pathik Bhowmik'),
('P508', 'Maleeha Mukhtar', 'Capability - Quality Team', 'Senior Content Lead', 'Gaurab Chatterjee'),
('P513', 'Samritha Subashraj', 'Capability - Quality Team', 'Senior Content Lead', 'Pratima'),
('P150', 'Nitish Singh', 'Capability - SEO Team', 'SEO Manager', 'Ajitesh Pandey'),
('P476', 'Sanket Mahure', 'Capability - SEO Team', 'SEO Growth Lead', 'Vaibhav Sawant'),
('P484', 'Mayur Varade', 'Capability - SEO Team', 'Director-SEO Growth', 'Anirudh Singla'),
('P493', 'Sushmita Balasubramanian', 'Capability - SEO Team', 'SEO Growth Lead', 'Vedanga Bandyopadhyay'),
('P507', 'Karan Shah', 'Capability - SEO Team', 'Assistant Manager-SEO', 'Sushmita Balasubramanian'),
('P510', 'Rewati Khare', 'Capability - SEO Team', 'SEO Growth Lead', 'Vedanga Bandyopadhyay'),
('P515', 'Swati Bhingardeve', 'Capability - SEO Team', 'Senior SEO Manager', 'Rewati Khare'),
('P516', 'Yash Chaudhari', 'Capability - SEO Team', 'Assistant Manager SEO', 'Anirudh Takkar'),
('P523', 'Prashant Singh Rawat', 'Capability - SEO Team', 'Assistant Manager-SEO', 'Rewati Khare'),
('P528', 'Onkar Gumdel', 'Capability - SEO Team', 'SEO Manager', 'Prithvi Pujari'),
('P530', 'Shahid Anwar', 'Capability - SEO Team', 'SEO Manager', 'Sanket Mahure'),
('P534', 'Ajitesh Pandey', 'Capability - SEO Team', 'Senior Director SEO', 'Anirudh Singla'),
('P539', 'Prashant Singh', 'Capability - SEO Team', 'Senior SEO Manager', 'Sushmita Balasubramanian'),
('P542', 'Vedanga Bandyopadhyay', 'Capability - SEO Team', 'AVP - SEO Growth', 'Anirudh Singla'),
('P545', 'Prithvi Pujari', 'Capability - SEO Team', 'SEO Growth Lead', 'Ajitesh Pandey'),
('P546', 'Saurabh Shinde', 'Capability - SEO Team', 'Assistant Manager SEO', 'Prithvi Pujari'),
('P550', 'Rashmi Oza', 'Capability - SEO Team', 'SEO Manager', 'Prithvi Pujari'),
('P559', 'Krishma Shah', 'Capability - SEO Team', 'SEO Business Manager', 'Irfan Pasha I'),
('P563', 'Manav Shah', 'Capability - SEO Team', 'Senior SEO Business Manager', 'Vaibhav Sawant'),
('P567', 'Karthik Nair', 'Capability - SEO Team', 'Group Head SEO', 'Mayur Varade'),
('P569', 'Vivek Chaudhary', 'Capability - SEO Team', 'SEO Business Manager', 'Rewati Khare'),
('P570', 'Vaibhav Sawant', 'Capability - SEO Team', 'Associate Director-SEO', 'Vedanga Bandyopadhyay'),
('P572', 'Crasto Leo Raymant', 'Capability - SEO Team', 'Group Head - SEO', 'Ajitesh Pandey'),
('P574', 'Avinash Choudhary', 'Capability - SEO Team', 'Senior SEO Business Manager', 'Irfan Pasha I'),
('P584', 'Siddhesh Sawant', 'Capability - SEO Team', 'Senior SEO Business Manager', 'Vaibhav Sawant'),
('P585', 'Pranav Jha', 'Capability - SEO Team', 'Senior SEO Analyst', 'Crasto Leo Raymant'),
('P588', 'Ankit Singh', 'Capability - SEO Team', 'SEO Business Manager', 'Rewati Khare'),
('P589', 'Samiran Dev', 'Capability - SEO Team', 'SEO Business Manager', 'Mayur Varade'),
('P591', 'Anirudh Takkar', 'Capability - SEO Team', 'Group Head - SEO', 'Mayur Varade'),
('P592', 'Krunal Ambre', 'Capability - SEO Team', 'SEO Manager', 'Vaibhav Sawant'),
('P593', 'Shaunli Mukherjee', 'Capability - SEO Team', 'Senior SEO Business Manager', 'Mayur Varade'),
('P594', 'Sahil Khan', 'Capability - SEO Team', 'SEO Manager', 'Mayur Varade'),
('P596', 'Dharmik Bhanushali', 'Capability - SEO Team', 'SEO Analyst', 'Rewati Khare'),
('P598', 'Aman Jain', 'Capability - SEO Team', 'SEO Analyst', 'Vaibhav Sawant'),
('P399', 'Jyotirmoyee Ghosh', 'Capability - Video Production Team', 'Associate Director - Video', 'Divya Ganapathy'),
('P486', 'Sohini Mukherjee', 'Capability - Video Production Team', 'Creative Producer', 'Divya Ganapathy'),
('P504', 'Geet Gangwani', 'Capability - Video Production Team', 'Creative Producer', 'Divya Ganapathy'),
('P533', 'Divya Ganapathy', 'Capability - Video Production Team', 'Director of Capability - Video Production', 'Sneha Iyer'),
('P564', 'Shanmathy Chackravarthi', 'Capability - Video Production Team', 'AD - Creative Producer', 'Divya Ganapathy'),
('P586', 'Jigar Somani', 'Capability - Video Production Team', 'Junior Producer', 'Jyotirmoyee Ghosh'),
('P571', 'Arya Gada', 'Central COE & Planning', 'Manager - COE', 'Shashwat Sood'),
('P112', 'Aamir Khan', 'Delivery Ops and CS', 'Senior Director - Vertical Service Delivery', 'Anirudh Singla'),
('P116', 'Karna Shah', 'Delivery Ops and CS', 'Senior BOPM', 'Sumit Shekhawat'),
('P127', 'Vanshika Khandelia', 'Delivery Ops and CS', 'Senior BOPM', 'Aamir Khan'),
('P148', 'Tiffany Fernandes', 'Delivery Ops and CS', 'Senior BOPM', 'Neema Jayadas'),
('P178', 'Anisha Jaisinghani', 'Delivery Ops and CS', 'Senior BOPM', 'Sumit Shekhawat'),
('P290', 'Rishabh Agarwal', 'Delivery Ops and CS', 'Senior BOPM', 'Neema Jayadas'),
('P308', 'Sumit Shekhawat', 'Delivery Ops and CS', 'Director - Vertical Service Delivery', 'Anirudh Singla'),
('P363', 'Rahul Singh', 'Delivery Ops and CS', 'Senior BOPM', 'Aamir Khan'),
('P369', 'Vrusha Mawani', 'Delivery Ops and CS', 'Group BOPM', 'Sneha Iyer'),
('P373', 'Janhavi Trivedi', 'Delivery Ops and CS', 'BOPM', 'Sumitha Shetty'),
('P378', 'Neema Jayadas', 'Delivery Ops and CS', 'AVP - Vertical Service Delivery', 'Anirudh Singla'),
('P413', 'Venkatesh Durgam', 'Delivery Ops and CS', 'Senior BOPM', 'Neema Jayadas'),
('P414', 'Sahil Singla', 'Delivery Ops and CS', 'Junior BOPM', 'Vanshika Khandelia'),
('P415', 'Mansi Velani', 'Delivery Ops and CS', 'Junior BOPM', 'Karna Shah'),
('P427', 'Vivek Teotia', 'Delivery Ops and CS', 'BOPM', 'Neema Jayadas'),
('P435', 'Karishma Sawlani', 'Delivery Ops and CS', 'BOPM', 'Vrusha Mawani'),
('P437', 'Aditya Shaw', 'Delivery Ops and CS', 'Director - Vertical Service Delivery', 'Anirudh Singla'),
('P465', 'Anshika Sharma', 'Delivery Ops and CS', 'Associate Project Manager', 'Neema Jayadas'),
('P467', 'Disha Bhanushali', 'Delivery Ops and CS', 'BOPM', 'Vrusha Mawani'),
('P472', 'Khushi Rajpurohit', 'Delivery Ops and CS', 'BOPM', 'Sumit Shekhawat'),
('P475', 'Risha Sinha', 'Delivery Ops and CS', 'Sr. BOPM', 'Ritu Shinde'),
('P478', 'Disha Suratwala', 'Delivery Ops and CS', 'Senior BOPM', 'Ritu Shinde'),
('P482', 'Tushar Walia', 'Delivery Ops and CS', 'Principle Account Engagement Lead', 'Aamir Khan'),
('P487', 'Ayushi Das', 'Delivery Ops and CS', 'Senior BOPM', 'Tushar Walia'),
('P488', 'Sumitha Shetty', 'Delivery Ops and CS', 'Group BOPM', 'Sneha Iyer'),
('P492', 'Rableen Kaur', 'Delivery Ops and CS', 'Group BOPM', 'Sneha Iyer'),
('P501', 'Romario Fernandes', 'Delivery Ops and CS', 'Junior BOPM', 'Vrusha Mawani'),
('P518', 'Ritu Shinde', 'Delivery Ops and CS', 'Group BOPM', 'Sneha Iyer'),
('P522', 'Sandhya Sharma', 'Delivery Ops and CS', 'BOPM', 'Sumit Shekhawat'),
('P525', 'Pranjal Wagh', 'Delivery Ops and CS', 'Junior BOPM', 'Sumitha Shetty'),
('P536', 'Ritisha Singh', 'Delivery Ops and CS', 'Junior BOPM', 'Aditya Shaw'),
('P537', 'Sonali Khurana', 'Delivery Ops and CS', 'AVP- Vertical Service Delivery', 'Anirudh Singla'),
('P538', 'Aishwarya Tarmase', 'Delivery Ops and CS', 'Junior BOPM', 'Aditya Shaw'),
('P541', 'Anushka Tiwari', 'Delivery Ops and CS', 'Junior BOPM', 'Aditya Shaw'),
('P544', 'Avinash Singh', 'Delivery Ops and CS', 'Junior BOPM', 'Tiffany Fernandes'),
('P547', 'Hemant Devraj', 'Delivery Ops and CS', 'Senior BOPM', 'Tushar Walia'),
('P549', 'Niharika Shukla', 'Delivery Ops and CS', 'Junior BOPM', 'Tiffany Fernandes'),
('P551', 'Saurabh Doshi', 'Delivery Ops and CS', 'Junior BOPM', 'Tiffany Fernandes'),
('P553', 'Aanal Kothari', 'Delivery Ops and CS', 'Junior BOPM', 'Risha Sinha'),
('P554', 'Sanchi Jhunjhunwala', 'Delivery Ops and CS', 'Group BOPM', 'Sneha Iyer'),
('P560', 'Aditya Bhalse', 'Delivery Ops and CS', 'BOPM', 'Sumit Shekhawat'),
('P566', 'Vidya Naveen', 'Delivery Ops and CS', 'BOPM', 'Sumit Shekhawat'),
('P573', 'Tania Vora', 'Delivery Ops and CS', 'BOPM', 'Aamir Khan'),
('P575', 'Anoshka Lopes', 'Delivery Ops and CS', 'BOPM', 'Aamir Khan'),
('P576', 'Aditi Kumawat', 'Delivery Ops and CS', 'Junior BOPM', 'Tushar Walia'),
('P577', 'Akshat Awasthi', 'Delivery Ops and CS', 'Junior BOPM', 'Tushar Walia'),
('P578', 'Manju Gond', 'Delivery Ops and CS', 'Junior BOPM', 'Tushar Walia'),
('P579', 'Tarun Singh Gangwar', 'Delivery Ops and CS', 'Junior BOPM', 'Tushar Walia'),
('P580', 'Yash Singh', 'Delivery Ops and CS', 'BOPM', 'Tushar Walia'),
('P581', 'Yuvraj Bhandari', 'Delivery Ops and CS', 'Junior BOPM', 'Tushar Walia'),
('P583', 'Indrajeet Singh', 'Delivery Ops and CS', 'Junior BOPM', 'Aditya Shaw'),
('P587', 'Khushi Ramnani', 'Delivery Ops and CS', 'Junior BOPM', 'Tushar Walia'),
('P590', 'Manvendra Singh', 'Delivery Ops and CS', 'Senior BOPM', 'Tushar Walia'),
('P595', 'Mohit Mishra', 'Delivery Ops and CS', 'Senior BOPM', 'Tushar Walia'),
('P597', 'Rishabh Sharma', 'Delivery Ops and CS', 'Junior BOPM', 'Tushar Walia'),
('P010', 'Rajesh Kanuri', 'Engineering', 'CTO', 'Anirudh Singla'),
('P125', 'Sumitra Soman', 'Engineering', 'Tech Lead', 'Pavan Pulluru'),
('P209', 'Pavan Pulluru', 'Engineering', 'Tech Lead', 'Rajesh Kanuri'),
('P338', 'Praveen Madiraju', 'Engineering', 'Senior Engineering Manager', 'Rajesh Kanuri'),
('P361', 'Pratiksha Mishra', 'Engineering', 'Senior Engineer', 'Pavan Pulluru'),
('P417', 'Suhasini Tiwari', 'Engineering', 'Senior Engineer', 'Praveen Madiraju'),
('P438', 'Khushali Vivek Kanjikar', 'Engineering', 'Senior Engineer', 'Praveen Madiraju'),
('P460', 'Bhargav Mistry', 'Engineering', 'Senior Engineer', 'Praveen Madiraju'),
('P462', 'Arun Reddy', 'Engineering', 'Senior Engineer', 'Praveen Madiraju'),
('P494', 'Yatin Shahane', 'Engineering', 'Engineer', 'Praveen Madiraju'),
('P006', 'Ankur Goel', 'Finance, Legal and Admin', 'CFO', 'Anirudh Singla'),
('P124', 'Ritesh Patil', 'Finance, Legal and Admin', 'Senior Manager - Accounts', 'Ankur Goel'),
('P135', 'Anuradha Sharma', 'Finance, Legal and Admin', 'Senior Director Finance', 'Anirudh Singla'),
('P158', 'Anil Kumar', 'Finance, Legal and Admin', 'Manager - Finance', 'Anuradha Sharma'),
('P211', 'Manju Vyas', 'Finance, Legal and Admin', 'Senior Manager Accounts', 'Ankur Goel'),
('P292', 'Suresh Joshi', 'Finance, Legal and Admin', 'Director - Finance', 'Anirudh Singla'),
('P328', 'Rama Mantri', 'Finance, Legal and Admin', 'Manager Finance Operations', 'Anuradha Sharma'),
('P332', 'Vimal Acharya', 'Finance, Legal and Admin', 'Senior Manager - Accounts', 'Ankur Goel'),
('P334', 'Krishna Rajak', 'Finance, Legal and Admin', 'Senior Manager - Accounts', 'Ankur Goel'),
('P371', 'Joel Antao', 'Finance, Legal and Admin', 'Director - Finance', 'Anirudh Singla'),
('P433', 'Rohit Singh', 'Finance, Legal and Admin', 'Senior Director-Finance', 'Anirudh Singla'),
('P443', 'Pranay Sehwani', 'Finance, Legal and Admin', 'Manager - Internal Audit', 'Anirudh Singla'),
('P454', 'Pranjal Mishra', 'Finance, Legal and Admin', 'Manager Finance', 'Anuradha Sharma'),
('P471', 'Tanmay Anand', 'Finance, Legal and Admin', 'Manager Finance', 'Anuradha Sharma'),
('P003', 'Anirudh Singla', 'Leadership', 'CEO', 'Anirudh Singla'),
('P014', 'Sneha Iyer', 'Leadership', 'COO', 'Anirudh Singla'),
('P031', 'Kishan Panpalia', 'Leadership', 'Chief of Staff', 'Anirudh Singla'),
('P408', 'Harsh Doshi', 'Leadership', 'Chief Revenue Officer', 'Anirudh Singla'),
('P099', 'Apoorva Verma Singh', 'Marketing and Demand Generation', 'Director - Marketing', 'Anirudh Singla'),
('P445', 'Kanika Manchanda', 'Marketing and Demand Generation', 'Senior Manager - Marketing', 'Apoorva Verma Singh'),
('P491', 'Indira Budhia', 'Marketing and Demand Generation', 'Group Manager - Marketing', 'Apoorva Verma Singh'),
('P038', 'Pankaj Bansal', 'Product - Design, Management', 'CPO', 'Anirudh Singla'),
('P139', 'Sumeet Yadav', 'Product - Design, Management', 'Director Product', 'Pankaj Bansal'),
('P432', 'Mukul Bhati', 'Product - Design, Management', 'Director Product', 'Anirudh Singla'),
('P439', 'Ishani Kumar', 'Product - Design, Management', 'Senior Manager Product', 'Mukul Bhati'),
('P244', 'Drashti Modh', 'Revenue - NN India Demand Gen', 'Director - Demand Gen', 'Apoorva Verma Singh'),
('P102', 'Akash Tomar', 'Revenue - NN India Sales', 'Director - Sales', 'Anirudh Singla'),
('P138', 'Sandipan Mukherjee', 'Revenue - NN India Sales', 'Director - Sales', 'Akash Tomar'),
('P176', 'Vivek Sharma', 'Revenue - NN India Sales', 'Director - Sales', 'Anirudh Singla'),
('P191', 'Soumitra Roy', 'Revenue - NN India Sales', 'Senior Director - Sales', 'Anirudh Singla'),
('P309', 'Suchet Khanna', 'Revenue - NN India Sales', 'Senior Director - Sales', 'Anirudh Singla'),
('P375', 'Akarsh Goyal', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Drashti Modh'),
('P407', 'Sahil Patil', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Akash Tomar'),
('P441', 'Vimal Karetia', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Suchet Khanna'),
('P446', 'Ravneet Singh', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Suchet Khanna'),
('P477', 'Praneet Sharma', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Sandipan Mukherjee'),
('P481', 'Lakshya Vij', 'Revenue - NN India Sales', 'Manager - Sales', 'Drashti Modh'),
('P483', 'Shrey Modi', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Akash Tomar'),
('P497', 'Mihir Khambhati', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Sandipan Mukherjee'),
('P521', 'Sai Baswa', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Akash Tomar'),
('P535', 'Anushka Singh', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Sandipan Mukherjee'),
('P543', 'Dhanil Munot', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Suchet Khanna'),
('P558', 'Hritik Sahay', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Akash Tomar'),
('P561', 'Rajul Khanna', 'Revenue - NN India Sales', 'Senior Manager - Sales', 'Soumitra Roy'),
('P133', 'Aman Tarwadi', 'Revenue - NN US Demand Gen', 'Director - US Sales', 'Anirudh Singla'),
('P200', 'Garima Wadhwa', 'Revenue - NN US Demand Gen', 'Director - Marketing', 'Apoorva Verma Singh'),
('P381', 'Aman Tomar', 'Revenue - NN US Demand Gen', 'Senior Manager - US Sales', 'Aman Tarwadi'),
('P562', 'Vinod Kumar', 'Revenue - NN US Demand Gen', 'Manager- US Sales', 'Aman Tarwadi'),
('P307', 'Tarun Kothari', 'Revenue - NN US Sales', 'Senior Manager - US Sales', 'Aman Tarwadi'),
('P347', 'Akshat Verma', 'Revenue - NN US Sales', 'Senior Manager - US Sales', 'Aman Tarwadi'),
('P426', 'Pratish Salian', 'Revenue - NN US Sales', 'Senior Manager - US Sales', 'Aman Tarwadi'),
('P440', 'Pratiksha Pansare', 'Revenue - NN US Sales', 'Senior Manager - US Sales', 'Aman Tarwadi'),
('P506', 'Tejas Vora', 'Revenue - NN US Sales', 'Senior Manager - US Sales', 'Aman Tarwadi'),
('P582', 'Samarth Mishra', 'Revenue - NN US Sales', 'SDR US', 'Harsh Doshi'),
('P260', 'Shashwat Sood', 'Supply Acquisition and Operations', 'Director - Supply Acquisition and Operations', 'Anirudh Singla'),
('P390', 'Sushmita Giri', 'Supply Acquisition and Operations', 'Manager - Supply Acquisition and Operations', 'Shashwat Sood'),
('P412', 'Mahak Garg', 'Supply Acquisition and Operations', 'Assistant Manager - Supply Acquisition and Operations', 'Shashwat Sood'),
('P436', 'Ankita Thakur', 'Supply Acquisition and Operations', 'Manager - Supply Acquisition and Operations', 'Shashwat Sood'),
('P461', 'Saparya Chakraborty', 'Supply Acquisition and Operations', 'Assistant Manager- Creative Talent Acquisition', 'Shashwat Sood'),
('P354', 'Trishita Jain', '', 'Senior Graphic Designer', 'Dhriti Goyal'),
('P434', 'Dhriti Goyal', '', 'Director of Product Marketing', 'Anirudh Singla')
)
INSERT INTO public.staffing_people
  (id, name, department, designation, reporting_manager, role_category, role_title, leaving, tbh)
SELECT
  i.id, i.name, i.department, i.designation, i.reporting_manager,
  '' AS role_category, '' AS role_title, false, false
FROM incoming i
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  department = EXCLUDED.department,
  designation = EXCLUDED.designation,
  reporting_manager = EXCLUDED.reporting_manager,
  leaving = false,
  updated_at = now();

-- Mark people not in the new roster as leaving (preserve their assignments).
UPDATE public.staffing_people
SET leaving = true, updated_at = now()
WHERE id NOT IN (
  'P394','P397','P452','P458','P479','P512','P520','P524','P527','P548','P555','P568',
  'P376','P385','P468','P498','P526','P532',
  'P028','P111','P122','P285','P364','P365','P366','P400','P464','P496','P503','P508','P513',
  'P150','P476','P484','P493','P507','P510','P515','P516','P523','P528','P530','P534','P539','P542','P545','P546','P550','P559','P563','P567','P569','P570','P572','P574','P584','P585','P588','P589','P591','P592','P593','P594','P596','P598',
  'P399','P486','P504','P533','P564','P586',
  'P571',
  'P112','P116','P127','P148','P178','P290','P308','P363','P369','P373','P378','P413','P414','P415','P427','P435','P437','P465','P467','P472','P475','P478','P482','P487','P488','P492','P501','P518','P522','P525','P536','P537','P538','P541','P544','P547','P549','P551','P553','P554','P560','P566','P573','P575','P576','P577','P578','P579','P580','P581','P583','P587','P590','P595','P597',
  'P010','P125','P209','P338','P361','P417','P438','P460','P462','P494',
  'P006','P124','P135','P158','P211','P292','P328','P332','P334','P371','P433','P443','P454','P471',
  'P003','P014','P031','P408',
  'P099','P445','P491',
  'P038','P139','P432','P439',
  'P244',
  'P102','P138','P176','P191','P309','P375','P407','P441','P446','P477','P481','P483','P497','P521','P535','P543','P558','P561',
  'P133','P200','P381','P562',
  'P307','P347','P426','P440','P506','P582',
  'P260','P390','P412','P436','P461',
  'P354','P434'
)
AND leaving = false;