
ALTER TABLE public.deal_rgy_weekly
  ADD COLUMN IF NOT EXISTS content text NOT NULL DEFAULT 'G',
  ADD COLUMN IF NOT EXISTS seo text NOT NULL DEFAULT 'G',
  ADD COLUMN IF NOT EXISTS supply text NOT NULL DEFAULT 'G',
  ADD COLUMN IF NOT EXISTS copy text NOT NULL DEFAULT 'G',
  ADD COLUMN IF NOT EXISTS design text NOT NULL DEFAULT 'G',
  ADD COLUMN IF NOT EXISTS video text NOT NULL DEFAULT 'G';
